### ISSUE TITLE
PatternStates not working as expected

### ISSUE THREAD

**Issue by max-dombrowski** [pattern-lab/patternlab-php#386]
If i add a pattern state by e.g. add @progress to one pattern, every other pattern that includes a pattern or is included by an other pattern get that state.

So adding state "progress" to a pattern, lets say "base-button", all my other patterns that have includes are on progress. Even if they don't include base-button.

In the docs http://patternlab.io/docs/pattern-states.html is can see there is some kind of state inheritance but this can not be the expected behaviour. 

Live example:
![image](https://cloud.githubusercontent.com/assets/25429198/24503579/f004b23a-1552-11e7-86ce-6907c6543179.png)
This pattern have no state suffix in filename, Child-pattern ist complete BUT the pattern ist set to in-review because some other pattern is set to in-review.

I used the node-edition earlier where states are working like a charm.
Any ideas?

**Comment by carolinmoll** [comment]
Same Problem here!

**Comment by alexcapes** [comment]
Same issue too.

**Comment by bradfrost** [comment]
@EvanLovely Is this something you've seen in your recent work touching the pattern states feature?

**Comment by EvanLovely** [comment]
Fixed in https://github.com/pattern-lab/patternlab-php-core/pull/139 and released in core [v2.8.4](https://github.com/pattern-lab/patternlab-php-core/releases/tag/v2.8.4)

**Comment by perriard** [comment]
I am still having this issue - using the twig standard edition. As I can see the core is still on version 2.0.0. Will the twig version be updated too?
